#!/usr/bin/env perl


use 5.010;
use strict;
use warnings;
use FindBin;
use Carp;
our $VERSION = '1.0';

BEGIN {
    unshift @INC, "$FindBin::Bin/../lib";
}
use Zoe;
use Getopt::Long;

my ($is_verbose, $application_config_file, $no_ddl, $do_replace_existing ) = undef;

GetOptions(
    'verbose!'   => \$is_verbose,
    'no_ddl!'    => \$no_ddl,
    'app_file=s' => \$application_config_file,
    'replace'    => \$do_replace_existing,
);

_usage() unless ($application_config_file);

croak
  "Could not read application description file: $application_config_file"
  unless ( -e $application_config_file );

Zoe->new->generate_application( application_config_file => $application_config_file, 
          no_ddl => $no_ddl,
          is_verbose => $is_verbose,  
          replace => $do_replace_existing,

        );

sub _usage {
    my $usage = <<"USAGE";
zoe-generator -verbose	Enables verbose logging
              -no_ddl	Tables will not be created
              -app_file	Application description file
              -replace  Replace existing controllers and views 
		 
USAGE
    say $usage and exit;
    return;
}

 
